### ISSUE TITLE
be able to add emogriefer params

### ISSUE THREAD

**Issue by netstyler** [burzum/cakephp-zurb-inky#1]
I need to be able to set specific params to the emogrifer css inliner.

Exmaple what I do set now:
```
$this->getEmogriefer()->disableInvisibleNodeRemoval();
$this->getEmogriefer()->disableStyleBlocksParsing();
```

At the moment there is no way to pass this settings to the render method:
```
 public function render($view = null, $layout = null)
    {
        $output = parent::render($view, $layout);
        $output = Pinky\transformString($output)->saveHTML();

        if (!empty($this->_css)) {
            // WHAT I NEED TO SET
            $this->getEmogriefer()->disableInvisibleNodeRemoval();
            $this->getEmogriefer()->disableStyleBlocksParsing();
            // WHAT I NEED TO SET
            $this->getEmogriefer()->setCss($this->_css);
            $this->getEmogriefer()->setHtml($output);

            return $this->getEmogriefer()->emogrify();
        }

        return $output;
    }
```

Do I miss something or is it not possible yet?

**Comment by burzum** [comment]
@netstyler why do you need to pass that? The method is public, just call `$this->getEmogriefer()->whatEver()` in your `AppView`.

Also your approach is wrong. You never implement application specific logic inside such an object.

**Comment by netstyler** [comment]
@burzum 
Got it thanks for the hint.

**Comment by burzum** [comment]
@netstyler in this case probably not in `AppView` but where ever this view instance is used.
